# Generated by Django 2.1.7 on 2021-04-29 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210429_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 29, 17, 53, 32, 828763)),
        ),
    ]
